### ISSUE TITLE
📊Tracking: monitoring services and mirrors availability

### ISSUE THREAD

**Issue by zxkane** [tuna/opentuna#33]
## 📊Tracking: monitoring services and mirror availability

It's an umbrella for monitoring feature requests.

- [ ] [monitor web portal](https://github.com/tuna/opentuna/issues/16)
- [ ] [monitor the availability of repos, such as automation testing installing software packages and python packages in centos/fedora/ubuntu/debian](https://github.com/tuna/opentuna/issues/64)
- [ ] monitor the healthy of tunasync manager
- [x] monitor the healthy of tunasync worker
- [x] monitor traffic bandwidth of content server, related to #19
- [ ] monitor mirroring tasks stuck/no progress for long time
- [ ] monitor error rate of distribution
- [ ] monitor the response time of first byte percentile
